### ISSUE TITLE
Item Request URL Wrapping

### ISSUE THREAD

**Issue by jajanet** [cseg-michigan/chez-betty#346]
Request items extend past their containers as seen here:
![image](https://user-images.githubusercontent.com/31081135/70962998-239ca980-2055-11ea-957e-5dac2596b682.png)
This could make navigating items cumbersome for both users and Chez Betty volunteers.

To replicate:
Log in, go to the Chez Betty User Admin page, and look at the requests under "Request New Item" 

This behavior is seen in Brave and Chrome (mobile and desktop), and likely others.

Fix Suggestions (would be happy to open a PR to get this fixed):

- If a URL is provided, hyperlink "store" with that URL (could cause security issues? not sure about what measures are currently taken to ensure no malicious links could be added though)
![image](https://user-images.githubusercontent.com/31081135/70963411-58f5c700-2056-11ea-85ea-ebbc839a2d65.png)

- Add CSS word wrapping (overflow-wrap: break-word;   word-break: break-word; for links)
![image](https://user-images.githubusercontent.com/31081135/70963137-a160b500-2055-11ea-9e6d-f12aca12ddc9.png)

**Comment by westbl** [comment]
@jajanet thanks for the suggestion!  I think that seeing the entire URL is helpful for us, regardless of the security implications, but adding text/link wrapping certainly seems like a good idea.  Would you mind submitting a PR with the change?

**Comment by jajanet** [comment]
Sure! Let me know if it needs any changes:))

**Comment by jajanet** [comment]
Fixed with #347
